# ● Load and explore data 
1.Import the required libraries and read the dataset.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv(r"C:\Users\Malang\Downloads\Dataset and relavant files - Python Project 1\fifa.csv")
data.head()

,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,Club Logo,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,https://cdn.sofifa.org/teams/2/light/241.png,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,https://cdn.sofifa.org/teams/2/light/45.png,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,https://cdn.sofifa.org/teams/2/light/73.png,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,https://cdn.sofifa.org/teams/2/light/11.png,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,https://cdn.sofifa.org/teams/2/light/10.png,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

2.Check the first few samples, shape, info of the data

In [4]:
data.shape

(18207, 60)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 60 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Photo                     18207 non-null  object
 4   Nationality               18207 non-null  object
 5   Flag                      18207 non-null  object
 6   Overall                   18207 non-null  int64
 7   Potential                 18207 non-null  int64
 8   Club                      17966 non-null  object
 9   Club Logo                 18207 non-null  object
 10  Value                     18207 non-null  object
 11  Wage                      18207 non-null  object
 12  Preferred Foot            18159 non-null  object
 13  International Reputation  18159 non-null  float64
 14  Weak Foot                 18159 non-null  float64
 15  Skill Moves               18159 non-null  float64
 16  Work Rate                 18159 non-null  object
 17  Body Type                 18159 non-null  object
 18  Position                  18147 non-null  object
 19  Jersey Number             18147 non-null  float64
 20  Joined                    16654 non-null  object
 21  Loaned From               1264 non-null   object
 22  Contract Valid Until      17918 non-null  object
 23  Height                    18159 non-null  object
 24  Weight                    18159 non-null  object
 25  Crossing                  18159 non-null  float64
 26  Finishing                 18159 non-null  float64
 27  HeadingAccuracy           18159 non-null  float64
 28  ShortPassing              18159 non-null  float64
 29  Volleys                   18159 non-null  float64
 30  Dribbling                 18159 non-null  float64
 31  Curve                     18159 non-null  float64
 32  FKAccuracy                18159 non-null  float64
 33  LongPassing               18159 non-null  float64
 34  BallControl               18159 non-null  float64
 35  Acceleration              18159 non-null  float64
 36  SprintSpeed               18159 non-null  float64
 37  Agility                   18159 non-null  float64
 38  Reactions                 18159 non-null  float64
 39  Balance                   18159 non-null  float64
 40  ShotPower                 18159 non-null  float64
 41  Jumping                   18159 non-null  float64
 42  Stamina                   18159 non-null  float64
 43  Strength                  18159 non-null  float64
 44  LongShots                 18159 non-null  float64
 45  Aggression                18159 non-null  float64
 46  Interceptions             18159 non-null  float64
 47  Positioning               18159 non-null  float64
 48  Vision                    18159 non-null  float64
 49  Penalties                 18159 non-null  float64
 50  Composure                 18159 non-null  float64
 51  Marking                   18159 non-null  float64
 52  StandingTackle            18159 non-null  float64
 53  SlidingTackle             18159 non-null  float64
 54  GKDiving                  18159 non-null  float64
 55  GKHandling                18159 non-null  float64
 56  GKKicking                 18159 non-null  float64
 57  GKPositioning             18159 non-null  float64
 58  GKReflexes                18159 non-null  float64
 59  Release Clause            16643 non-null  object
dtypes: float64(38), int64(4), object(18)
memory usage: 8.3+ MB

3.Drop the columns which you think redundant for the analysis.

In [6]:
data.drop('Photo', axis=1, inplace=True)
data.drop('Flag', axis=1, inplace=True)
data.drop('Club Logo', axis=1, inplace=True)

data.head()

,ID,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,158023,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,Left,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,20801,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,Right,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,190871,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,Right,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,193080,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,Right,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,192985,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,Right,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

# Data Cleaning and Preprocessing

Convert the columns "Value", "Wage", "Release Clause" to float datatype

In [7]:
df=data.copy()

In [15]:
df['Value']= df['Value'].str.replace('€','')

In [16]:
df['Wage']= df['Wage'].str.replace('€','')

In [17]:
df.Wage

0        565K
1        405K
2        290K
3        260K
4        355K
         ...
18202      1K
18203      1K
18204      1K
18205      1K
18206      1K
Name: Wage, Length: 18207, dtype: object

In [36]:
def convert_suffix_to_float(i):
    suffix = i[-1].upper()
    if suffix == 'M':
        return float(i[:-1]) * 1_000_000
    elif suffix == 'K':
        return float(i[:-1]) * 1_000
    else:
        return float(i)